export const compoundProjectData: string[][] = [
  [
    "General plan of the site",
    "House floor plans",
    "Floor plans with connections for sanitary equipment",
    "Light and color solutions for facades",
    "House visualizations",
    "House facades",
    "Longitudinal section of the house",
    "Cross section of a house",
    "Foundation plan",
    "Specification of foundation materials, reinforcement",
    "Floor plans",
    "Specification of floor materials, reinforcement",
  ],
  [
    "Drawings of interfloor stairs",
    "Masonry plans",
    "Lintel plans, wall material specifications",
    "Roof plan, rafter system plan",
    "Nodes of junctions, overhangs, passages",
    "Specification of roofing materials",
    "Constructive solutions for waterproofing",
    "Vapor barrier, insulation",
    "Schemes of construction of terraces and canopies, junction units",
    "Drawings of decorative elements of the house",
    "Specification of window and door openings",
    " Fastening units for window and door units",
    "Specification and characteristics of finishing materials for the house",
  ],
];
